---
- name: create system group
  group:
    name: "{{ sockd_group }}"
    system: true
    state: present
  when: sockd_group != "root"
  tags: sockd

- name: create system user
  user:
    name: "{{ sockd_user }}"
    system: true
    shell: "/sbin/nologin"
    group: "{{ sockd_group }}"
  when: sockd_user != "root"
  tags: sockd

- name: copy binary file
  copy:
    src: "{{ role_path }}/files/sockd"
    dest: "{{ sockd_binary_install_dir }}/sockd"
    owner: root
    group: root
    mode: 0755
  tags: sockd

- name: generate config files
  template:
    src: "sockd.conf.j2"
    dest: "/etc/sockd.conf"
    owner: "{{ sockd_user }}"
    group: "{{ sockd_group }}"
    mode: 0640
  notify: restart sshsocks
  tags: 
    - sockd
    - sockd_acls

- name: generate config files
  template:
    src: "sockd.conf.j2"
    dest: "{{ sockd_config }}"
    owner: "{{ sockd_user }}"
    group: "{{ sockd_group }}"
    mode: 0640
  notify: restart sshsocks
  tags: 
    - sockd
    - sockd_acls

- name: copy systemd service unit
  template:
    src: sockd.service.j2
    dest: /etc/systemd/system/sockd.service
    owner: root
    group: root
    mode: 0644
  notify: restart sockd
  tags: sockd

- name: start and enable service
  systemd:
    daemon_reload: true
    name: sockd
    enabled: true
    state: started
  tags: sockd

- name: caddy html config
  template:
    src: caddy_socks.html.j2
    dest: "{{ sockd_caddy_webserver_path }}/socks.html"
    owner: "{{ sockd_caddy_user }}"
    group: "{{ sockd_caddy_group }}"
    mode: 0644
  when: sockd_caddy_generate_html_output
  become: true
  tags:
    - sockd
    - sockd_acls

- name: consul service config
  template:
    src: consul.service.json.j2
    dest: "/etc/consul.d/{{ item.id }}.json"
    owner: consul
    group: consul
    mode: 0644
  with_items: "{{ consul_service_config }}"
  when: sockd_consul_service_register
  notify: reload consul
  become: true
  tags:
    - sockd
    - consul
