---
- import_tasks: facts.yml
  become: true
  tags: sockd

- import_tasks: install.yml
  become: true
  tags: sockd

- import_tasks: configure.yml
  become: true
  tags: sockd

- import_tasks: selinux.yml
  become: true
  when: ansible_selinux.status == "enabled"
  tags: sockd

- import_tasks: firewall.yml
  become: true
  when: ("'active' in ufw_status.stdout") or ("'running' in firewalld_status.stdout")
  tags: sockd

- name: start and enable service
  systemd:
    daemon_reload: true
    name: "{{ sockd_bin }}"
    enabled: true
    state: started
  become: true
  tags: sockd