---
- name: restart sshsocks
  systemd:
    name: sshsocks
    state: restarted
  become: true
  tags: sshsocks

- name: reload consul
  systemd:
    name: consul
    state: reloaded
  become: true
  tags:
    - socks
    - consul
