---
- name: restart sockd
  ansible.builtin.systemd:
    daemon_reload: true
    name: "{{ sockd_bin }}"
    state: restarted
  become: true
  tags: sockd
  
- name: reload sockd
  ansible.builtin.systemd:
    name: "{{ sockd_bin }}"
    state: reloaded
  become: true
  tags: sockd

- name: reload ufw
  ansible.builtin.systemd:
    name: ufw
    state: reloaded
  when: ansible_os_family == 'Debian'
  become: true
  tags: sockd

- name: reload firewalld
  ansible.builtin.systemd:
    name: firewalld
    state: reloaded
  when: ansible_os_family == 'RedHat'
  become: true
  tags: sockd
