---
- name: restart sockd
  systemd:
    name: sockd
    state: restarted
  become: true
  tags: sockd

- name: reload consul
  systemd:
    name: consul
    state: reloaded
  become: true
  tags:
    - sockd
    - consul
