---
- name: restart sockd
  systemd:
    daemon_reload: true
    name: sockd
    state: restarted
  tags: sockd
  
- name: reload sockd
  systemd:
    name: sockd
    state: reloaded
  tags: sockd

- name: reload consul
  systemd:
    name: consul
    state: reloaded
  tags:
    - sockd
    - consul

- name: reload firewalld
  service:
    name: firewalld
    state: reloaded
  tags: sockd
